package br.com.devedores.app;
import android.app.*;import android.os.*;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;
public class AddLoanActivity extends Activity{
 DataStore ds;Models.Client client;EditText title,principal,interest,installments,firstDay,notes;Spinner freq;Calendar due=Calendar.getInstance();LinearLayout preview;
 @Override public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);client=ds.client(getIntent().getStringExtra("clientId"));build();}
 void build(){LinearLayout p=Ui.col(this);LinearLayout top=Ui.row(this);Button back=Ui.btnDark(this,"‹ Voltar");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,82),Ui.dp(this,46)));LinearLayout tt=Ui.col(this);tt.setPadding(Ui.dp(this,10),0,0,0);tt.addView(Ui.title(this,"Novo empréstimo",23));tt.addView(Ui.label(this,client.name));top.addView(tt,new LinearLayout.LayoutParams(0,Ui.dp(this,54),1));p.addView(top);Ui.gap(this,p,16);
   LinearLayout hero=Ui.softCard(this,Ui.GOLD);hero.addView(Ui.eyebrow(this,"NOVO CONTRATO"));hero.addView(Ui.text(this,"Informe o valor, juros e frequência. O app calcula a dívida e agenda todas as parcelas.",14));p.addView(hero);Ui.gap(this,p,14);
   title=Ui.field(this,"Nome do contrato");principal=Ui.field(this,"Valor emprestado (R$)");interest=Ui.field(this,"Juros (%)");installments=Ui.field(this,"Quantidade de parcelas");EditText[] es={title,principal,interest,installments};for(EditText e:es){p.addView(e,new LinearLayout.LayoutParams(-1,Ui.dp(this,56)));Ui.gap(this,p,9);}p.addView(Ui.eyebrow(this,"PERIODICIDADE"));freq=new Spinner(this);freq.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Semanal","Quinzenal","Mensal"}));p.addView(freq,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));Ui.gap(this,p,10);
   p.addView(Ui.eyebrow(this,"PRIMEIRO VENCIMENTO"));firstDay=Ui.field(this,"Data");firstDay.setFocusable(false);firstDay.setText(dateText(due.getTimeInMillis()));firstDay.setOnClickListener(v->pickDate());p.addView(firstDay,new LinearLayout.LayoutParams(-1,Ui.dp(this,56)));Ui.gap(this,p,10);
   notes=Ui.field(this,"Observações do contrato");p.addView(notes,new LinearLayout.LayoutParams(-1,Ui.dp(this,90)));Ui.gap(this,p,12);
   preview=Ui.card(this);preview.addView(Ui.label(this,"Resumo do contrato aparecerá aqui."));p.addView(preview);Ui.gap(this,p,12);
   Button save=Ui.btn(this,"Criar contrato e agendar parcelas");save.setOnClickListener(v->save());p.addView(save,new LinearLayout.LayoutParams(-1,Ui.dp(this,54)));setContentView(p);android.text.TextWatcher tw=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){updatePreview();}public void afterTextChanged(android.text.Editable e){}};principal.addTextChangedListener(tw);interest.addTextChangedListener(tw);installments.addTextChangedListener(tw);}
 String dateText(long x){return new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date(x));}
 void updatePreview(){try{double p=Double.parseDouble(principal.getText().toString().replace(',','.'));double ip=Double.parseDouble(interest.getText().toString().replace(',','.'));int n=Integer.parseInt(installments.getText().toString());double iv=p*ip/100d,total=p+iv,parcela=total/n;preview.removeAllViews();preview.addView(Ui.eyebrow(this,"PRÉVIA"));preview.addView(Ui.text(this,String.format(Locale.getDefault(),"Emprestado: %s\nJuros: %s  •  Total: %s\n%d parcelas de %s",money(p),money(iv),money(total),n,money(parcela)),15));}catch(Exception ignored){}}
 String money(double x){return String.format(Locale.getDefault(),"R$ %.2f",x);}
 void pickDate(){new DatePickerDialog(this,(v,y,m,d)->{due.set(y,m,d,10,0,0);firstDay.setText(dateText(due.getTimeInMillis()));},due.get(Calendar.YEAR),due.get(Calendar.MONTH),due.get(Calendar.DAY_OF_MONTH)).show();}
 void save(){try{double p=Double.parseDouble(principal.getText().toString().replace(',','.'));double ip=Double.parseDouble(interest.getText().toString().replace(',','.'));int n=Integer.parseInt(installments.getText().toString());if(p<=0||n<=0||ip<0)throw new Exception();Models.Loan l=new Models.Loan();l.title=title.getText().toString().trim().isEmpty()?"Empréstimo":title.getText().toString().trim();l.notes=notes.getText().toString();l.principal=p;l.interestPercent=ip;l.interestValue=p*ip/100d;l.total=p+l.interestValue;l.installments=n;l.frequency=freq.getSelectedItem().toString();l.installmentAmount=l.total/n;l.firstDue=due.getTimeInMillis();client.loans.add(l);ds.save();AlarmScheduler.scheduleAllInstallments(this,client,l);Toast.makeText(this,String.format(Locale.getDefault(),"Contrato criado • %s",money(l.total)),Toast.LENGTH_LONG).show();finish();}catch(Exception e){Toast.makeText(this,"Preencha valor, juros e quantidade de parcelas corretamente.",Toast.LENGTH_LONG).show();}}
}
